Repository AY2021S1-CS2113T-F11-3/tp, pull requests merged in 2020-10, with the labels that each got.

#21 Add rate feature for each flashcard under revision
  src/main/java/Kaji.java
  src/main/java/commands/ReviseCommand.java
  src/main/java/manager/card/Card.java
  src/main/java/ui/Ui.java
Labels: priority.High, type.Story

#28 Junit revise command
  src/main/java/commands/HelpCommand.java
  src/main/java/commands/ReviseCommand.java
  src/main/java/ui/Ui.java
  src/test/java/commands/ReviseCommandTest.java
Labels: priority.High, type.Story

#29 Add feature to remove cards
  src/main/java/commands/RemoveCommand.java
  src/main/java/manager/chapter/CardList.java
  src/main/java/parser/Parser.java
  src/main/java/ui/Ui.java
  src/test/java/parser/ParserTest.java
Labels: priority.High, type.Story

#44 Finalise file structure
  src/main/java/access/Access.java
  src/main/java/commands/AddChapterCommand.java
  src/main/java/commands/AddModuleCommand.java
  src/main/java/commands/GoChapterCommand.java
  src/main/java/commands/GoModuleCommand.java
  src/main/java/manager/admin/Admin.java
  src/main/java/manager/admin/ModuleList.java
  src/main/java/manager/chapter/CardList.java
  src/main/java/manager/chapter/Chapter.java
  src/main/java/manager/module/ChapterList.java
  src/main/java/manager/module/Module.java
  src/main/java/storage/Storage.java
  src/main/java/ui/Ui.java
Labels: priority.High, type.Enhancement

#45 Fix date for revise command
  src/main/java/commands/ReviseCommand.java
  src/main/java/manager/card/Card.java
  src/main/java/scheduler/Scheduler.java
  src/main/java/ui/Ui.java
  src/test/java/scheduler/SchedulerTest.java
Labels: priority.High, type.Enhancement

#30 Add the ability to edit the content of a card
  src/main/java/Kaji.java
  src/main/java/commands/AddCommand.java
  src/main/java/commands/Command.java
  src/main/java/commands/EditCommand.java
  src/main/java/exception/IncorrectAccessLevelException.java
  src/main/java/exception/InvalidInputException.java
  src/main/java/manager/card/Card.java
  src/main/java/manager/chapter/Chapter.java
  src/main/java/manager/module/Module.java
  src/main/java/parser/Parser.java
  src/main/java/ui/Ui.java
  src/test/java/parser/ParserTest.java
Labels: priority.High, type.Story

#48 List cards only at chapter level
  src/main/java/commands/EditCommand.java
  src/main/java/commands/ListCommand.java
  src/main/java/parser/Parser.java
Labels: priority.High, type.Enhancement

#56 Add list command
  questions.txt
  src/main/java/Kaji.java
  src/main/java/commands/AddChapterCommand.java
  src/main/java/commands/AddCommand.java
  src/main/java/commands/AddModuleCommand.java
  src/main/java/commands/BackChapterCommand.java
  src/main/java/commands/BackModuleCommand.java
  src/main/java/commands/Command.java
  src/main/java/commands/GoChapterCommand.java
  src/main/java/commands/GoModuleCommand.java
  src/main/java/commands/ListCommand.java
  src/main/java/manager/card/Card.java
  src/main/java/parser/Parser.java
  src/main/java/storage/Storage.java
  src/main/java/ui/Ui.java
Labels: priority.High, type.Story

#55 Fix revise command to get cards based on access
  src/main/java/Kaji.java
  src/main/java/commands/Command.java
  src/main/java/commands/ReviseCommand.java
  src/main/java/manager/module/ChapterList.java
  src/main/java/parser/Parser.java
  src/main/java/ui/Ui.java
Labels: priority.High, type.Enhancement

#58 Enhance the feature of adding cards at chapter level only
  src/main/java/access/Access.java
  src/main/java/commands/AddCommand.java
  src/main/java/commands/EditCommand.java
  src/main/java/parser/Parser.java
  src/test/java/parser/ParserTest.java
Labels: priority.High, type.Enhancement

#60 Add feature remove module and chapter
  src/main/java/commands/RemoveCommand.java
  src/main/java/parser/Parser.java
  src/main/java/storage/Storage.java
Labels: priority.High, type.Story

#62 Add Features: Rating new chapters and List due chapters
  src/main/java/commands/AddChapterCommand.java
  src/main/java/commands/GoChapterCommand.java
  src/main/java/commands/ListCommand.java
  src/main/java/commands/ListDueCommand.java
  src/main/java/commands/ReviseCommand.java
  src/main/java/manager/card/Card.java
  src/main/java/manager/chapter/Chapter.java
  src/main/java/parser/Parser.java
  src/main/java/scheduler/Scheduler.java
  src/main/java/storage/Storage.java
  src/main/java/ui/Ui.java
  src/test/java/scheduler/SchedulerTest.java
Labels: priority.High, type.Story

#63 Save edited name
  src/main/java/commands/BackChapterCommand.java
  src/main/java/commands/BackCommand.java
  src/main/java/commands/BackModuleCommand.java
  src/main/java/commands/EditCommand.java
  src/main/java/commands/GoChapterCommand.java
  src/main/java/commands/GoCommand.java
  src/main/java/commands/GoModuleCommand.java
  src/main/java/parser/Parser.java
  src/main/java/storage/Storage.java
  src/main/java/ui/Ui.java
Labels: priority.High, type.Enhancement

#64 Add assert and logging statements
  src/main/java/commands/RemoveCommand.java
  src/main/java/commands/ReviseCommand.java
Labels: priority.Medium, type.Enhancement

#65 Enhance edit command
  src/main/java/Kaji.java
  src/main/java/commands/AddCommand.java
  src/main/java/commands/BackCommand.java
  src/main/java/commands/Command.java
  src/main/java/commands/EditCommand.java
  src/main/java/commands/ExitCommand.java
  src/main/java/commands/GoCommand.java
  src/main/java/commands/HelpCommand.java
  src/main/java/commands/ListCommand.java
  src/main/java/commands/ListDueCommand.java
  src/main/java/commands/RemoveCommand.java
  src/main/java/commands/ReviseCommand.java
  src/main/java/parser/Parser.java
Labels: priority.Medium, type.Enhancement

#66 Add assertions for EditCommand, add and list cards
  src/main/java/commands/AddCommand.java
  src/main/java/commands/EditCommand.java
  src/main/java/commands/ListCommand.java
  src/main/java/parser/Parser.java
Labels: priority.High, type.Task

#69 load and save previous interval
  data/admin/cs2113 1/topic 1.txt
  src/main/java/manager/card/Card.java
  src/main/java/parser/Parser.java
  src/main/java/storage/Storage.java
Labels: priority.High, type.Enhancement

#73 Enhancement - revise not due and string format
  src/main/java/Kaji.java
  src/main/java/access/Access.java
  src/main/java/commands/AddCommand.java
  src/main/java/commands/BackCommand.java
  src/main/java/commands/EditCommand.java
  src/main/java/commands/GoCommand.java
  src/main/java/commands/ListCommand.java
  src/main/java/commands/ListDueCommand.java
  src/main/java/commands/RemoveCommand.java
  src/main/java/commands/ReviseCommand.java
  src/main/java/common/Messages.java
  src/main/java/parser/Parser.java
  src/main/java/storage/Storage.java
  src/main/java/ui/Ui.java
Labels: priority.High, type.Enhancement

#76 Add HistoryCommand
  src/main/java/Kaji.java
  src/main/java/access/Access.java
  src/main/java/commands/GoCommand.java
  src/main/java/commands/HistoryCommand.java
  src/main/java/commands/ListCommand.java
  src/main/java/commands/ReviseCommand.java
  src/main/java/exception/InvalidFileFormatException.java
  src/main/java/manager/admin/Admin.java
  src/main/java/manager/history/History.java
  src/main/java/manager/history/HistoryList.java
  src/main/java/parser/Parser.java
  src/main/java/storage/Storage.java
  src/main/java/ui/Ui.java
Labels: priority.High, type.Enhancement

#81 Bug back command
  src/main/java/META-INF/MANIFEST.MF
  src/main/java/access/Access.java
  src/main/java/common/Messages.java
  src/main/java/parser/Parser.java
  src/main/java/ui/Ui.java
  src/test/java/parser/ParserTest.java
Labels: priority.High, severity.Low, type.Bug

#86 Reorganised code for output message
  src/main/java/commands/AddCommand.java
  src/main/java/commands/EditCommand.java
  src/main/java/commands/ListCommand.java
  src/main/java/parser/Parser.java
Labels: type.Task

#88 fix history storage issue
  src/main/java/commands/ReviseCommand.java
  src/main/java/storage/Storage.java
Labels: priority.High, type.Enhancement

#85 Feature preview
  src/main/java/commands/ListDueCommand.java
  src/main/java/commands/PreviewCommand.java
  src/main/java/parser/Parser.java
  src/main/java/scheduler/Scheduler.java
  src/main/java/ui/Ui.java
Labels: priority.High, type.Enhancement

#92 Reschedule chapter due date
  src/main/java/commands/RescheduleCommand.java
  src/main/java/parser/Parser.java
  src/main/java/ui/Ui.java
Labels: priority.High, type.Enhancement

#87 Feature rating
  .gitignore
  data/admin/cs2113 1/topic 1.txt
  docs/DeveloperGuide.md
  docs/UML/printPrompt1.png
  docs/UML/printPrompt1.puml
  docs/UML/printPrompt2.puml
  docs/UserGuide.md
  docs/image/rateCommand_correct.jpg
  docs/image/rateCommand_emptyCard.jpg
  docs/image/rateCommand_wrongFormat1.jpg
  docs/image/rateCommand_wrongFormat2.jpg
  docs/image/showrateCommand_correct.jpg
  docs/image/showrateCommand_wrongFormat.jpg
  src/main/java/commands/AddCommand.java
  src/main/java/commands/ListCommand.java
  src/main/java/commands/RateCommand.java
  src/main/java/commands/ReviseCommand.java
  src/main/java/commands/ShowRateCommand.java
  src/main/java/manager/card/Card.java
  src/main/java/manager/chapter/Chapter.java
  src/main/java/parser/Parser.java
  src/main/java/storage/Storage.java
  src/main/java/ui/Ui.java
Labels: priority.High, type.Enhancement

#89 Enhancement selective scheduler
  src/main/java/Kaji.java
  src/main/java/commands/Command.java
  src/main/java/commands/ExcludeCommand.java
  src/main/java/commands/ListDueCommand.java
  src/main/java/commands/PreviewCommand.java
  src/main/java/exception/ExclusionFileException.java
  src/main/java/parser/Parser.java
  src/main/java/storage/Storage.java
  src/main/java/ui/Ui.java
Labels: priority.High, type.Enhancement

#95 Updated DG for Implementation: 4.6 and 4.8
  docs/DeveloperGuide.md
  src/main/java/commands/ExcludeCommand.java
  src/main/java/commands/ListDueCommand.java
  src/main/java/commands/PreviewCommand.java
  src/main/java/parser/Parser.java
Labels: priority.High, type.Task

#90 fix history
  src/main/java/manager/admin/Admin.java
  src/main/java/manager/history/HistoryList.java
  src/main/java/ui/Ui.java
Labels: priority.High, type.Enhancement

#96 update DG
  docs/DeveloperGuide.md
Labels: priority.High, type.Task

#97 Updated DG for Implementation: 4.1
  docs/DeveloperGuide.md
Labels: priority.High, type.Task

#98 Add deletion of chapter from due when chapter is deleted
  src/main/java/commands/RemoveCommand.java
  src/main/java/storage/Storage.java
Labels: severity.Medium, type.Bug

#99 Update Developer Guide
  docs/DeveloperGuide.md
Labels: priority.High, type.Task

#101 Add logging feature
  src/main/java/Kaji.java
  src/main/java/commands/RemoveCommand.java
  src/main/java/commands/ReviseCommand.java
  src/main/java/common/KajiLog.java
  src/main/java/storage/Storage.java
Labels: type.Task

#103 Added user guide format
  docs/UserGuide.md
Labels: type.Task

#104 Updated format of user guide
  docs/UserGuide.md
Labels: type.Task

#106 Added developer guide format
  docs/DeveloperGuide.md
Labels: type.Task

#108 Task log storage
  src/main/java/Kaji.java
  src/main/java/commands/AddCommand.java
  src/main/java/commands/GoCommand.java
  src/main/java/commands/RemoveCardCommand.java
  src/main/java/commands/RemoveChapterCommand.java
  src/main/java/common/Messages.java
  src/main/java/storage/Storage.java
  src/main/java/ui/Ui.java
Labels: type.Task

#114 Feature add separated command for GoCommand, BackCommand and AddCommand
  src/main/java/commands/AddCardCommand.java
  src/main/java/commands/AddChapterCommand.java
  src/main/java/commands/AddCommand.java
  src/main/java/commands/AddModuleCommand.java
  src/main/java/commands/BackAdminCommand.java
  src/main/java/commands/BackCommand.java
  src/main/java/commands/BackModuleCommand.java
  src/main/java/commands/Command.java
  src/main/java/commands/GoChapterCommand.java
  src/main/java/commands/GoCommand.java
  src/main/java/commands/GoModuleCommand.java
  src/main/java/common/Messages.java
  src/main/java/parser/Parser.java
Labels: type.Task

#120 Feature rating: Delete rate command and add storage to revise
  docs/DeveloperGuide.md
  src/main/java/commands/AddCardCommand.java
  src/main/java/commands/AddChapterCommand.java
  src/main/java/commands/AddModuleCommand.java
  src/main/java/commands/BackModuleCommand.java
  src/main/java/commands/ListCommand.java
  src/main/java/commands/RateCommand.java
  src/main/java/commands/ReviseCommand.java
  src/main/java/manager/chapter/Chapter.java
  src/main/java/parser/Parser.java
  src/main/java/ui/Ui.java
Labels: severity.High, type.Bug

#118 Add prepareResult in RemoveCommand
  docs/DeveloperGuide.md
  src/main/java/commands/RemoveCardCommand.java
  src/main/java/commands/RemoveChapterCommand.java
  src/main/java/commands/RemoveCommand.java
  src/main/java/commands/RemoveModuleCommand.java
  src/main/java/parser/Parser.java
Labels: type.Task

#121 Feature edit, list card, add card
  src/main/java/Kaji.java
  src/main/java/commands/AddCardCommand.java
  src/main/java/commands/AddChapterCommand.java
  src/main/java/commands/AddCommand.java
  src/main/java/commands/AddModuleCommand.java
  src/main/java/commands/BackAdminCommand.java
  src/main/java/commands/BackCommand.java
  src/main/java/commands/BackModuleCommand.java
  src/main/java/commands/Command.java
  src/main/java/commands/EditCardCommand.java
  src/main/java/commands/EditChapterCommand.java
  src/main/java/commands/EditCommand.java
  src/main/java/commands/EditModuleCommand.java
  src/main/java/commands/GoChapterCommand.java
  src/main/java/commands/GoCommand.java
  src/main/java/commands/GoModuleCommand.java
  src/main/java/commands/ListCardCommand.java
  src/main/java/commands/ListCommand.java
  src/main/java/common/Messages.java
  src/main/java/exception/DuplicateDataException.java
  src/main/java/parser/Parser.java
  src/main/java/storage/Storage.java
Labels: type.Task

#117 Separate list command
  docs/UserGuide.md
  src/main/java/commands/ListChapterCommand.java
  src/main/java/commands/ListCommand.java
  src/main/java/commands/ListModuleCommand.java
  src/main/java/parser/Parser.java
  src/test/java/parser/ParserTest.java
Labels: type.Task

#123 Updated DG
  docs/DG_Images/EditCardSequenceDiagram.png
  docs/DG_Images/EditChapterSequenceDiagram.png
  docs/DG_Images/EditModuleSequenceDiagram.png
  docs/DG_Images/LogicClassDiagram.png
  docs/DG_Images/LogicSequenceDiagram.png
  docs/DeveloperGuide.md
  docs/UML/Command.puml
  docs/UML/EditCardSequenceDiagram.puml
  docs/UML/EditChapterSequenceDiagram.puml
  docs/UML/EditModuleSequenceDiagram.puml
  docs/UML/LogicClassDiagram.puml
  docs/UML/LogicSequenceDiagram.puml
  docs/UML/style.puml
Labels: type.Task

#124 Updated part of DG allocated and renamed some variables to better names
  docs/DeveloperGuide.md
  docs/images/ExcludeCommand.png
  docs/images/addChapterToExclusion.png
  docs/images/addModuleToExclusion.png
  docs/images/removeChapterFromExclusion.png
  docs/images/removeModuleFromExclusion.png
  src/main/java/commands/AddCardCommand.java
  src/main/java/commands/ExcludeCommand.java
  src/main/java/storage/Storage.java
Labels: priority.High, type.Task

#126 Fix due date issue for list command
  src/main/java/Kaji.java
  src/main/java/commands/GoCommand.java
  src/main/java/commands/GoModuleCommand.java
  src/main/java/commands/ListChapterCommand.java
  src/main/java/storage/Storage.java
  src/main/java/ui/Ui.java
Labels: severity.Low, type.Bug

#129 Refactored RescheduleCommand
  src/main/java/commands/RescheduleCommand.java
Labels: type.Task

#131 Updated DG and renamed some variables to more descriptive names
  docs/DeveloperGuide.md
  src/main/java/commands/ListDueCommand.java
  src/main/java/commands/PreviewCommand.java
  src/main/java/commands/ReviseCommand.java
  src/main/java/scheduler/Scheduler.java
  src/main/java/storage/Storage.java
  src/test/java/scheduler/SchedulerTest.java
Labels: type.Bug, type.Task

#132 Updated UG
  docs/UserGuide.md
Labels: priority.High, type.Task

#133 Add Implementation and Architecture for Developer Guide
  docs/DeveloperGuide.md
  docs/UML/AccessModuleCommand.png
  docs/UML/AccessModuleCommand.puml
  docs/UML/AccessModuleCommandClass.png
  docs/UML/AccessModuleCommandClass.puml
  docs/UML/AddChapterCommand.png
  docs/UML/AddChapterCommand.puml
  docs/UML/AddChapterCommandClass.png
  docs/UML/AddChapterCommandClass.puml
  docs/UML/AddModuleCommand.png
  docs/UML/AddModuleCommand.puml
  docs/UML/AddModuleCommandClass.png
  docs/UML/AddModuleCommandClass.puml
  docs/UML/ShowRateCommand.png
  docs/UML/ShowRateCommand.puml
  docs/UML/ShowRateCommandClass.png
  docs/UML/ShowRateCommandClass.puml
  docs/UML/model.png
  docs/UML/model.puml
  docs/UML/printPrompt2.png
  src/main/java/commands/ShowRateCommand.java
Labels: type.Task

#130 Add Architecture diagram for DG
  docs/DeveloperGuide.md
  docs/UML/Architecture.png
  docs/UML/listcard_seq_diagram.png
  docs/UML/listcard_seq_diagram.puml
  docs/UML/listchap_seq_diagram.png
  docs/UML/listchap_seq_diagram.puml
  docs/UML/listhistory_seq_diagram.png
  docs/UML/listhistory_seq_diagram.puml
  docs/UML/listmod_seq_diagram.png
  docs/UML/listmod_seq_diagram.puml
  src/main/java/Kaji.java
  src/main/java/commands/Command.java
  src/main/java/commands/HistoryCommand.java
  src/main/java/commands/ListCardsCommand.java
  src/main/java/commands/ListChaptersCommand.java
  src/main/java/commands/ListCommand.java
  src/main/java/commands/ListModulesCommand.java
  src/main/java/commands/ReviseCommand.java
  src/main/java/exception/DuplicateDataException.java
  src/main/java/exception/EmptyFileException.java
  src/main/java/exception/IncorrectAccessLevelException.java
  src/main/java/exception/InvalidFileFormatException.java
  src/main/java/parser/Parser.java
Labels: type.Task

#134 Update uml diagrams in DG
  docs/DG_Images/removecard_seq_diagram.png
  docs/DG_Images/removechap_seq_diagram.png
  docs/DG_Images/removemod_seq_diagram.png
  docs/DG_Images/returnmod_seq_diagram.png
  docs/DG_Images/revise_seq_diagram.png
  docs/DG_Images/ui_component.PNG
  docs/DeveloperGuide.md
  docs/UML/removecard_seq_diagram.png
  docs/UML/removecard_seq_diagram.puml
  docs/UML/removechap_seq_diagram.png
  docs/UML/removechap_seq_diagram.puml
  docs/UML/removemod_seq_diagram.png
  docs/UML/removemod_seq_diagram.puml
  docs/UML/returnmod_seq_diagram.png
  docs/UML/returnmod_seq_diagram.puml
  docs/UML/revise_seq_diagram.png
  docs/UML/revise_seq_diagram.puml
  docs/UML/ui_component.puml
Labels: type.Task

#135 Updated DG with add card and reschedule feature
  docs/DG_Images/AddCardSequenceDiagram.png
  docs/DG_Images/EditCardSequenceDiagram.png
  docs/DG_Images/EditChapterSequenceDiagram.png
  docs/DG_Images/EditModuleSequenceDiagram.png
  docs/DG_Images/LogicClassDiagram.png
  docs/DG_Images/LogicSequenceDiagram.png
  docs/DG_Images/RescheduleChapterSequenceDiagram.png
  docs/DeveloperGuide.md
  docs/UML/AddCardSequenceDiagram.puml
  docs/UML/EditCardSequenceDiagram.puml
  docs/UML/EditChapterSequenceDiagram.puml
  docs/UML/EditModuleSequenceDiagram.puml
  docs/UML/LogicClassDiagram.puml
  docs/UML/LogicSequenceDiagram.puml
  docs/UML/RescheduleChapterSequenceDiagram.puml
  src/main/java/commands/RescheduleCommand.java
Labels: type.Task

#136 Updated DG
  docs/DeveloperGuide.md
Labels: type.Task

#137 Standarize diagrams in dg and ug
  docs/DeveloperGuide.md
Labels: type.Task

#139 Add remove and back module feature to UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/BackMod1.PNG
  docs/images/BackMod2.PNG
  docs/images/BackMod3.PNG
  docs/images/RemoveCard1.PNG
  docs/images/RemoveCard2.PNG
  docs/images/RemoveCard3.PNG
  docs/images/RemoveChap2.PNG
  docs/images/RemoveChap3.PNG
  docs/images/RemoveMod1.PNG
  docs/images/RemoveMod2.PNG
  docs/images/RemoveMod3.PNG
  docs/images/Revise2.PNG
  docs/images/Revise3.PNG
  docs/images/Revise4.PNG
  docs/images/Revise5.PNG
  docs/images/Revise6.PNG
  docs/images/Revise7.PNG
  docs/images/Revise8.PNG
  docs/images/kaji.PNG
Labels: type.Task

#140 Fix formatting issue
  docs/UserGuide.md
  docs/images/BackMod2.PNG
  docs/images/BackMod3.PNG
  docs/images/ReturnMod1.PNG
Labels: type.Task

#141 update UG
  docs/UG_Images/edit_module.png
  docs/UG_Images/exit.png
  docs/UG_Images/help1.png
  docs/UG_Images/help2.png
  docs/UG_Images/history.png
  docs/UG_Images/history_Date.png
  docs/UG_Images/list_chapter.png
  docs/UG_Images/list_module.png
  docs/UserGuide.md
  src/main/java/storage/Storage.java
Labels: type.Task

#142 Updated UG - Edit, Reschedule chapter and Add, List, Edit card
  docs/UG_Images/AddCard1.png
  docs/UG_Images/AddCard2.png
  docs/UG_Images/EditCard1.png
  docs/UG_Images/EditCard2.png
  docs/UG_Images/EditCard3.png
  docs/UG_Images/EditCard4.png
  docs/UG_Images/EditChapter1.png
  docs/UG_Images/EditChapter2.png
  docs/UG_Images/EditChapter3.png
  docs/UG_Images/EditChapter4.png
  docs/UG_Images/ListCard1.png
  docs/UG_Images/ListCard2.png
  docs/UG_Images/RescheduleChapter1.png
  docs/UG_Images/RescheduleChapter2.png
  docs/UG_Images/RescheduleChapter3.png
  docs/UG_Images/RescheduleChapter4.png
  docs/UserGuide.md
Labels: type.Task

#143 Updated UG
  docs/UG_Images/due.png
  docs/UG_Images/dueComplete.png
  docs/UG_Images/excludeLess.png
  docs/UG_Images/excludeLess2.png
  docs/UG_Images/excludeLess2Chapter.png
  docs/UG_Images/excludeLess2ChapterChapterName.png
  docs/UG_Images/excludeLess2ChapterChapterName2.png
  docs/UG_Images/excludeLess2ChapterComplete.png
  docs/UG_Images/excludeLess2ChapterModuleName.png
  docs/UG_Images/excludeLess2ChapterModuleName2.png
  docs/UG_Images/excludeLess2Module.png
  docs/UG_Images/excludeLess2ModuleComplete.png
  docs/UG_Images/excludeLess2ModuleModuleName.png
  docs/UG_Images/excludeLess2ModuleModuleName2.png
  docs/UG_Images/excludeMore.png
  docs/UG_Images/excludeMore2.png
  docs/UG_Images/excludeMore2Chapter.png
  docs/UG_Images/excludeMore2ChapterChapterName.png
  docs/UG_Images/excludeMore2ChapterChapterName2.png
  docs/UG_Images/excludeMore2ChapterComplete.png
  docs/UG_Images/excludeMore2ChapterModuleName.png
  docs/UG_Images/excludeMore2ChapterModuleName2.png
  docs/UG_Images/excludeMore2Module.png
  docs/UG_Images/excludeMore2ModuleComplete.png
  docs/UG_Images/excludeMore2ModuleModuleName.png
  docs/UG_Images/excludeMore2ModuleModuleName2.png
  docs/UG_Images/preview.png
  docs/UG_Images/previewComplete.png
  docs/UG_Images/prompt.png
  docs/UserGuide.md
Labels: priority.High, type.Task

#144 Added the "go" and "back" commands for the Module Level in UG.
  docs/UG_Images/back.png
  docs/UG_Images/backComplete.png
  docs/UG_Images/moduleGo.png
  docs/UG_Images/moduleGoResult.png
  docs/UserGuide.md
Labels: priority.High, type.Task

#145 Update UG
  docs/UserGuide.md
Labels: type.Task
