Repository AY2021S1-CS2113T-F11-3/tp, pull requests merged in 2020-11, with the labels that each got.

#138 Bug Fixes
  src/main/java/manager/chapter/Chapter.java
  src/main/java/storage/Storage.java
Labels: severity.Medium, type.Bug

#146 update DG
  docs/UML/listcard_seq_diagram.png
  docs/UML/listcard_seq_diagram.puml
  docs/UML/listchap_seq_diagram.png
  docs/UML/listchap_seq_diagram.puml
  docs/UML/listhistory_seq_diagram.png
  docs/UML/listhistory_seq_diagram.puml
  docs/UML/listmod_seq_diagram.png
  docs/UML/listmod_seq_diagram.puml
  src/main/java/Kaji.java
  src/main/java/commands/Command.java
  src/main/java/commands/HistoryCommand.java
  src/main/java/commands/ListCardsCommand.java
  src/main/java/commands/ListChaptersCommand.java
  src/main/java/commands/ListCommand.java
  src/main/java/commands/ListModulesCommand.java
  src/main/java/exception/EmptyFileException.java
Labels: type.Task

#195 Refactor parser
  src/main/java/access/Access.java
  src/main/java/commands/AddCardCommand.java
  src/main/java/commands/AddCommand.java
  src/main/java/commands/BackAdminCommand.java
  src/main/java/commands/BackCommand.java
  src/main/java/commands/BackModuleCommand.java
  src/main/java/commands/EditChapterCommand.java
  src/main/java/commands/EditCommand.java
  src/main/java/commands/EditModuleCommand.java
  src/main/java/commands/GoChapterCommand.java
  src/main/java/commands/GoModuleCommand.java
  src/main/java/commands/RemoveCommand.java
  src/main/java/commands/RescheduleCommand.java
  src/main/java/common/Messages.java
  src/main/java/parser/AddCommandParser.java
  src/main/java/parser/BackCommandParser.java
  src/main/java/parser/EditCommandParser.java
  src/main/java/parser/ExcludeCommandParser.java
  src/main/java/parser/ExitCommandParser.java
  src/main/java/parser/GoCommandParser.java
  src/main/java/parser/HelpCommandParser.java
  src/main/java/parser/HistoryCommandParser.java
  src/main/java/parser/ListCommandParser.java
  src/main/java/parser/ListDueCommandParser.java
  src/main/java/parser/Parser.java
  src/main/java/parser/PreviewCommandParser.java
  src/main/java/parser/RemoveCommandParser.java
  src/main/java/parser/RescheduleCommandParser.java
  src/main/java/parser/ReviseCommandParser.java
  src/main/java/parser/ShowRateCommandParser.java
  src/main/java/storage/Storage.java
  src/main/java/storage/StorageParser.java
  src/test/java/parser/ParserTest.java
Labels: priority.High, type.Task

#197 Remove rate feature from UG
  docs/UserGuide.md
Labels: severity.Low, type.Bug

#196 Refactor Storage class
  src/main/java/Kaji.java
  src/main/java/storage/Storage.java
  src/main/java/storage/StorageLoad.java
  src/main/java/storage/StorageWrite.java
Labels: priority.High, type.Task

#198 Split Exclude and Include into two commands
  src/main/java/commands/ExcludeCommand.java
  src/main/java/commands/IncludeCommand.java
  src/main/java/parser/IncludeCommandParser.java
  src/main/java/parser/Parser.java
  src/main/java/ui/Ui.java
Labels: severity.Medium, type.Task

#199 Resolve duplicate name of module and chapter
  src/main/java/commands/AddChapterCommand.java
  src/main/java/commands/AddModuleCommand.java
  src/main/java/commands/GoChapterCommand.java
  src/main/java/commands/GoModuleCommand.java
  src/main/java/common/Messages.java
  src/main/java/manager/admin/ModuleList.java
  src/main/java/manager/module/ChapterList.java
  src/main/java/parser/AddCommandParser.java
  src/main/java/parser/GoCommandParser.java
Labels: severity.Medium, type.Bug

#200 Docs update dg
  docs/AboutUs.md
  docs/DG_Images/ReviseGetCards.png
  docs/DG_Images/ReviseGetChap.png
  docs/DG_Images/ReviseNotDue.png
  docs/DG_Images/removecard_seq_diagram.png
  docs/DG_Images/removechap_seq_diagram.png
  docs/DG_Images/removemod_seq_diagram.png
  docs/DG_Images/returnmod_seq_diagram.png
  docs/DG_Images/revise_seq_diagram.png
  docs/DG_Images/ui_component.PNG
  docs/DeveloperGuide.md
  docs/UML/ReivseGetChap.puml
  docs/UML/ReviseGetCards.puml
  docs/UML/ReviseNotDue.puml
  docs/UML/removecard_seq_diagram.puml
  docs/UML/removechap_seq_diagram.puml
  docs/UML/removemod_seq_diagram.puml
  docs/UML/returnmod_seq_diagram.puml
  docs/UML/revise_seq_diagram.puml
  docs/UML/ui_component.puml
Labels: type.Task

#202 Fix pe issues
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/commands/HistoryCommand.java
  src/main/java/manager/history/History.java
  src/main/java/storage/StorageLoad.java
Labels: severity.Medium, type.Bug, type.Task

#204 Added exclude include successful completion messages
  src/main/java/commands/ExcludeCommand.java
  src/main/java/commands/IncludeCommand.java
  src/main/java/ui/Ui.java
Labels: priority.High, type.Enhancement

#205 Updated UG to include "include" command
  docs/UG_Images/excludeChapter.png
  docs/UG_Images/excludeChapterChapterFilled.png
  docs/UG_Images/excludeChapterChapterPrompt.png
  docs/UG_Images/excludeChapterModuleFilled.png
  docs/UG_Images/excludeChapterModulePrompt.png
  docs/UG_Images/excludeChapterResult.png
  docs/UG_Images/excludeLess.png
  docs/UG_Images/excludeLess2.png
  docs/UG_Images/excludeLess2Chapter.png
  docs/UG_Images/excludeLess2ChapterChapterName.png
  docs/UG_Images/excludeLess2ChapterChapterName2.png
  docs/UG_Images/excludeLess2ChapterComplete.png
  docs/UG_Images/excludeLess2ChapterModuleName.png
  docs/UG_Images/excludeLess2ChapterModuleName2.png
  docs/UG_Images/excludeLess2Module.png
  docs/UG_Images/excludeLess2ModuleComplete.png
  docs/UG_Images/excludeLess2ModuleModuleName.png
  docs/UG_Images/excludeLess2ModuleModuleName2.png
  docs/UG_Images/excludeModule.png
  docs/UG_Images/excludeModuleModuleFilled.png
  docs/UG_Images/excludeModuleModulePrompt.png
  docs/UG_Images/excludeModuleResult.png
  docs/UG_Images/excludeMore.png
  docs/UG_Images/excludeMore2.png
  docs/UG_Images/excludeMore2Chapter.png
  docs/UG_Images/excludeMore2ChapterChapterName.png
  docs/UG_Images/excludeMore2ChapterChapterName2.png
  docs/UG_Images/excludeMore2ChapterComplete.png
  docs/UG_Images/excludeMore2ChapterModuleName.png
  docs/UG_Images/excludeMore2ChapterModuleName2.png
  docs/UG_Images/excludeMore2Module.png
  docs/UG_Images/excludeMore2ModuleComplete.png
  docs/UG_Images/excludeMore2ModuleModuleName.png
  docs/UG_Images/excludeMore2ModuleModuleName2.png
  docs/UG_Images/includeChapter.png
  docs/UG_Images/includeChapterChapterFilled.png
  docs/UG_Images/includeChapterChapterPrompt.png
  docs/UG_Images/includeChapterModuleFilled.png
  docs/UG_Images/includeChapterModulePrompt.png
  docs/UG_Images/includeChapterResult.png
  docs/UG_Images/includeModule.png
  docs/UG_Images/includeModuleModuleFilled.png
  docs/UG_Images/includeModuleModulePrompt.png
  docs/UG_Images/includeModuleResult.png
  docs/UserGuide.md
Labels: priority.High, type.Task

#206 Junitest
  src/main/java/commands/RemoveModuleCommand.java
  src/test/data/admin/module/chapter1
  src/test/java/commands/RemoveCardCommandTest.java
  src/test/java/commands/RemoveChapterCommandTest.java
  src/test/java/commands/RemoveModuleCommandTest.java
  src/test/java/commands/ReviseCommandTest.java
  src/test/java/parser/ParserTest.java
Labels: type.Task

#207 Fixed UG image errors
  docs/UG_Images/excludeChapter.png
  docs/UG_Images/excludeChapterChapterFilled.png
  docs/UG_Images/excludeChapterChapterPrompt.png
  docs/UG_Images/excludeChapterModuleFilled.png
  docs/UG_Images/excludeChapterModulePrompt.png
  docs/UG_Images/excludeChapterResult.png
  docs/UG_Images/excludeModule.png
  docs/UG_Images/excludeModuleModuleFilled.png
  docs/UG_Images/excludeModuleModulePrompt.png
  docs/UG_Images/excludeModuleResult.png
  docs/UG_Images/includeChapter.png
  docs/UG_Images/includeChapterChapterFilled.png
  docs/UG_Images/includeChapterChapterPrompt.png
  docs/UG_Images/includeChapterModuleFilled.png
  docs/UG_Images/includeChapterModulePrompt.png
  docs/UG_Images/includeChapterResult.png
  docs/UG_Images/includeModule.png
  docs/UG_Images/includeModuleModuleFilled.png
  docs/UG_Images/includeModuleModulePrompt.png
  docs/UG_Images/includeModuleResult.png
  docs/UserGuide.md
Labels: severity.High, type.Task

#208 Update Jiayi's PPP draft
  docs/team/gua-guargia.md
Labels: type.Task

#209 Add PPP
  docs/team/johndoe.md
  docs/team/zhu-ze-yu.md
Labels: type.Task

#210 Added PPP
  docs/team/darticune.md
Labels: priority.High, type.Task

#211 Docs ppp
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/kaji.PNG
  docs/team/neojiaern.md
Labels: type.Task

#214 fix architecture for DG
  docs/DG_Images/Architecture.png
  docs/DeveloperGuide.md
  docs/UML/Architecture.png
Labels: type.Task

#215 Bug edit command
  src/main/java/Kaji.java
  src/main/java/commands/AddCardCommand.java
  src/main/java/commands/AddChapterCommand.java
  src/main/java/commands/AddModuleCommand.java
  src/main/java/commands/Command.java
  src/main/java/commands/EditCardCommand.java
  src/main/java/commands/EditChapterCommand.java
  src/main/java/commands/EditCommand.java
  src/main/java/commands/EditModuleCommand.java
  src/main/java/commands/HistoryCommand.java
  src/main/java/commands/ReviseCommand.java
  src/main/java/common/Messages.java
  src/main/java/exception/DuplicateDataException.java
  src/main/java/exception/StorageDataException.java
  src/main/java/manager/admin/ModuleList.java
  src/main/java/manager/card/Card.java
  src/main/java/manager/chapter/CardList.java
  src/main/java/manager/module/ChapterList.java
  src/main/java/parser/AddCommandParser.java
  src/main/java/parser/EditCommandParser.java
  src/main/java/parser/GoCommandParser.java
  src/main/java/parser/ParserUtil.java
  src/main/java/storage/Storage.java
  src/main/java/storage/StorageLoad.java
  src/main/java/storage/StorageWrite.java
  src/main/java/ui/Ui.java
Labels: priority.High, severity.Medium, type.Bug

#217 Add junit tests for various Command classes
  src/main/java/commands/AddCardCommand.java
  src/main/java/commands/AddCommand.java
  src/main/java/commands/EditCardCommand.java
  src/main/java/commands/EditChapterCommand.java
  src/main/java/commands/EditCommand.java
  src/main/java/commands/EditModuleCommand.java
  src/main/java/commands/RescheduleCommand.java
  src/main/java/parser/EditCommandParser.java
  src/test/data/admin/module/chapter1
  src/test/data/admin/test
  src/test/java/commands/AddCardCommandTest.java
  src/test/java/commands/EditCardCommandTest.java
  src/test/java/commands/EditChapterCommandTest.java
  src/test/java/commands/EditModuleCommandTest.java
  src/test/java/commands/ListCardsCommandTest.java
  src/test/java/commands/RescheduleCommandTest.java
  src/test/java/parser/AddCommandParserTest.java
Labels: type.Task

#219 Added JavaDoc comments
  src/main/java/Kaji.java
  src/main/java/commands/AddCardCommand.java
  src/main/java/commands/AddCommand.java
  src/main/java/commands/Command.java
  src/main/java/commands/EditCardCommand.java
  src/main/java/commands/EditChapterCommand.java
  src/main/java/commands/EditCommand.java
  src/main/java/commands/EditModuleCommand.java
  src/main/java/commands/ListCardsCommand.java
  src/main/java/commands/ListCommand.java
  src/main/java/commands/RescheduleCommand.java
  src/main/java/common/Messages.java
  src/main/java/exception/IncorrectAccessLevelException.java
  src/main/java/exception/InvalidInputException.java
  src/main/java/exception/StorageDataException.java
  src/main/java/manager/admin/ModuleList.java
  src/main/java/manager/card/Card.java
  src/main/java/manager/chapter/CardList.java
  src/main/java/manager/module/ChapterList.java
  src/main/java/parser/AddCommandParser.java
  src/main/java/parser/EditCommandParser.java
  src/main/java/parser/ExitCommandParser.java
  src/main/java/parser/ListCommandParser.java
  src/main/java/parser/Parser.java
  src/main/java/parser/ParserUtil.java
  src/main/java/parser/RescheduleCommandParser.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/storage/Storage.java
  src/main/java/storage/StorageLoad.java
  src/main/java/storage/StorageParser.java
  src/main/java/storage/StorageWrite.java
  src/main/java/ui/Ui.java
  src/test/java/seedu/duke/DukeTest.java
Labels: type.Task

#218 Add junit test
  data/history/2020-11-02.txt
  src/main/java/commands/RemoveCommand.java
  src/main/java/commands/ReviseCommand.java
  src/main/java/ui/Ui.java
  src/test/java/commands/RemoveCardCommandTest.java
  src/test/java/commands/RemoveChapterCommandTest.java
  src/test/java/commands/RemoveModuleCommandTest.java
  src/test/java/commands/ReviseCommandTest.java
  src/test/java/parser/ParserTest.java
  src/test/java/parser/RemoveCommandParserTest.java
  src/test/java/parser/ReviseCommandParserTest.java
Labels: type.Task

#220 Add junit test
  src/main/java/commands/HelpCommand.java
  src/main/java/commands/HistoryCommand.java
  src/main/java/parser/HelpCommandParser.java
  src/main/java/parser/HistoryCommandParser.java
  src/main/java/storage/StorageLoad.java
  src/main/java/storage/StorageWrite.java
  src/test/java/commands/HistoryCommandTest.java
  src/test/java/parser/HistoryCommandParserTest.java
  src/test/java/parser/ParserTest.java
Labels: type.Task

#221 Add author and test
  src/main/java/commands/HelpCommand.java
  src/main/java/commands/HistoryCommand.java
  src/main/java/parser/HelpCommandParser.java
  src/main/java/parser/HistoryCommandParser.java
  src/test/java/parser/ParserTest.java
Labels: type.Task

#222 Go command read in index instead of module name
  docs/DeveloperGuide.md
  docs/UML/AccessModuleCommand.png
  docs/UML/AccessModuleCommand.puml
  docs/UML/AccessModuleCommandClass.png
  docs/UML/AccessModuleCommandClass.puml
  docs/UML/AddModuleCommand.puml
  docs/UML/style.puml
  src/main/java/commands/GoChapterCommand.java
  src/main/java/commands/GoCommand.java
  src/main/java/commands/GoModuleCommand.java
  src/main/java/common/Messages.java
  src/main/java/parser/GoCommandParser.java
Labels: severity.Medium, type.Bug

#225 Updated AddCardClassDiagram
  docs/DG_Images/AddCardClassDiagram.png
  docs/UML/AddCardClassDiagram.puml
Labels: type.Task

#226 DG Update
  docs/DG_Images/excludeSeq.png
  docs/DG_Images/includeSeq.png
  docs/DG_Images/listDueSeq.png
  docs/DG_Images/previewSeq.png
  docs/DG_Images/storage.png
  docs/DeveloperGuide.md
  docs/UG_Images/moduleGo.png
  docs/UG_Images/moduleGoResult.png
  docs/UML/excludeSeq.puml
  docs/UML/includeSeq.puml
  docs/UML/listDueSeq.puml
  docs/UML/previewSeq.puml
  docs/UML/storage.puml
  docs/UML/style.puml
  docs/UserGuide.md
  src/main/java/commands/PreviewCommand.java
  src/main/java/storage/Storage.java
  src/main/java/storage/StorageLoad.java
  src/main/java/storage/StorageWrite.java
Labels: type.Task

#234 change diagrams
  docs/DG_Images/Architecture.png
  docs/DeveloperGuide.md
  docs/UML/listcard_seq_diagram.png
  docs/UML/listcard_seq_diagram.puml
  docs/UML/listchap_seq_diagram.png
  docs/UML/listchap_seq_diagram.puml
  docs/UML/listhistory_seq_diagram.png
  docs/UML/listhistory_seq_diagram.puml
  docs/UML/listmod_seq_diagram.png
  docs/UML/listmod_seq_diagram.puml
Labels: type.Task

#238 Update diagrams
  docs/DG_Images/ReviseCommandClassDiagram.png
  docs/DG_Images/ReviseCommandSeqDiagram.png
  docs/DG_Images/ReviseGetCards.png
  docs/DG_Images/ReviseGetChap.png
  docs/DG_Images/ReviseNotDue.png
  docs/DG_Images/UiComponent.PNG
  docs/DeveloperGuide.md
  docs/UG_Images/BackMod1.PNG
  docs/UG_Images/BackMod2.PNG
  docs/UG_Images/RemoveCard1.PNG
  docs/UG_Images/RemoveCard2.PNG
  docs/UG_Images/RemoveChap1.PNG
  docs/UG_Images/RemoveChap2.PNG
  docs/UG_Images/RemoveMod1.PNG
  docs/UG_Images/RemoveMod2.PNG
  docs/UG_Images/Revise1.png
  docs/UG_Images/Revise2.PNG
  docs/UG_Images/Revise3.PNG
  docs/UG_Images/Revise4.PNG
  docs/UG_Images/Revise5.PNG
  docs/UG_Images/Revise6.PNG
  docs/UG_Images/Revise7.PNG
  docs/UG_Images/Revise8.PNG
  docs/UML/ReviseCommandClassDiagram.puml
  docs/UML/ReviseGetCards.puml
  docs/UML/ReviseGetChap.puml
  docs/UML/ReviseNotDue.puml
  docs/UserGuide.md
  docs/images/BackMod1.PNG
  docs/images/BackMod2.PNG
  docs/images/BackMod3.PNG
  docs/images/RemoveCard1.PNG
  docs/images/RemoveCard2.PNG
  docs/images/RemoveCard3.PNG
  docs/images/RemoveChap2.PNG
  docs/images/RemoveChap3.PNG
  docs/images/RemoveMod1.PNG
  docs/images/RemoveMod2.PNG
  docs/images/RemoveMod3.PNG
  docs/images/Revise2.PNG
  docs/images/Revise3.PNG
  docs/images/Revise4.PNG
  docs/images/Revise5.PNG
  docs/images/Revise6.PNG
  docs/images/Revise7.PNG
  docs/images/Revise8.PNG
  docs/images/removecard.PNG
  docs/images/removechapter.PNG
  docs/images/removemodule.PNG
  docs/images/revise_due.PNG
  docs/images/revise_nocards.PNG
  docs/images/revise_notdue.PNG
Labels: type.Task

#239 Updated UG diagrams
  docs/UG_Images/AddCard1.png
  docs/UG_Images/AddCard2.png
  docs/UG_Images/AdminLevel.png
  docs/UG_Images/ChapterLevel.png
  docs/UG_Images/EditCard1.png
  docs/UG_Images/EditCard2.png
  docs/UG_Images/EditCard3.png
  docs/UG_Images/EditCard4.png
  docs/UG_Images/EditChapter1.png
  docs/UG_Images/EditChapter2.png
  docs/UG_Images/EditChapter3.png
  docs/UG_Images/EditChapter4.png
  docs/UG_Images/Index.png
  docs/UG_Images/ListCard1.png
  docs/UG_Images/ListCard2.png
  docs/UG_Images/ModuleLevel.png
  docs/UG_Images/RescheduleChapter1.png
  docs/UG_Images/RescheduleChapter2.png
  docs/UG_Images/RescheduleChapter3.png
  docs/UG_Images/RescheduleChapter4.png
  docs/UML/listchap_seq_diagram.png
  docs/UML/listhistory_seq_diagram.png
  docs/UML/listmod_seq_diagram.png
  docs/UserGuide.md
  docs/_config.yml
Labels: type.Task

#240 Add use cases
  docs/DeveloperGuide.md
Labels: type.Task

#243 Add javadoc
  src/main/java/commands/RemoveCardCommand.java
  src/main/java/commands/RemoveChapterCommand.java
  src/main/java/commands/RemoveCommand.java
  src/main/java/commands/RemoveModuleCommand.java
  src/main/java/commands/ReviseCommand.java
  src/main/java/parser/RemoveCommandParser.java
  src/main/java/parser/ReviseCommandParser.java
  src/main/java/storage/Storage.java
  src/main/java/storage/StorageWrite.java
  src/main/java/ui/Ui.java
Labels: type.Task

#244 Added some instructions for manual testing
  docs/DeveloperGuide.md
Labels: type.Task

#248 Add manual instructions for testing
  docs/DeveloperGuide.md
Labels: type.Task

#246 add class diagrams
  docs/DG_Images/listcard_class_diagram.png
  docs/DG_Images/listchap_class_diagram.png
  docs/DG_Images/listhistory_class_diagram.png
  docs/DG_Images/listmod_class_diagram.png
  docs/DeveloperGuide.md
  docs/UML/listcard_class_diagram.puml
  docs/UML/listchap_class_diagram.puml
  docs/UML/listhistory_class_diagram.puml
  docs/UML/listmod_class_diagram.puml
Labels: type.Task

#250 Docs fixes
  docs/DeveloperGuide.md
  docs/README.md
  docs/team/neojiaern.md
Labels: type.Task

#251 Dg2
  docs/DG_Images/AccessChapterClass.png
  docs/DG_Images/BackAdminClass.png
  docs/DG_Images/backAdmin.png
  docs/DG_Images/excludeClass.png
  docs/DG_Images/excludeSeq.png
  docs/DG_Images/goChapter.png
  docs/DG_Images/includeClass.png
  docs/DG_Images/includeSeq.png
  docs/DG_Images/listDueClass.png
  docs/DG_Images/listDueSeq.png
  docs/DG_Images/previewClass.png
  docs/DG_Images/previewSeq.png
  docs/DeveloperGuide.md
  docs/UML/AccessChapterClass.puml
  docs/UML/BackAdminClass.puml
  docs/UML/backAdminSeq.puml
  docs/UML/excludeClass.puml
  docs/UML/excludeSeq.puml
  docs/UML/goChapter.puml
  docs/UML/includeClass.puml
  docs/UML/includeSeq.puml
  docs/UML/listDueClass.puml
  docs/UML/listDueSeq.puml
  docs/UML/previewClass.puml
  docs/UML/previewSeq.puml
  docs/UserGuide.md
  src/main/java/commands/ExcludeCommand.java
  src/main/java/commands/IncludeCommand.java
  src/main/java/commands/ListDueCommand.java
  src/main/java/commands/PreviewCommand.java
  src/main/java/storage/StorageLoad.java
  src/main/java/storage/StorageWrite.java
  src/main/java/ui/Ui.java
Labels: type.Task

#252 Updated instructions for manual testing
  docs/DeveloperGuide.md
Labels: type.Task

#254 Fix user guide
  docs/DeveloperGuide.md
  docs/UG_Images/EditModule1.png
  docs/UG_Images/EditModule2.png
  docs/UG_Images/EditModule3.png
  docs/UG_Images/EditModule4.png
  docs/UG_Images/edit_module.png
  docs/UG_Images/exit.png
  docs/UG_Images/exit1.png
  docs/UG_Images/exit2.png
  docs/UG_Images/help1.png
  docs/UG_Images/help2.png
  docs/UG_Images/history.png
  docs/UG_Images/history1.png
  docs/UG_Images/history2.png
  docs/UG_Images/history3.png
  docs/UG_Images/history_Date.png
  docs/UG_Images/list_chapter.png
  docs/UG_Images/list_chapter1.png
  docs/UG_Images/list_chapter2.png
  docs/UG_Images/list_module.png
  docs/UG_Images/list_module1.png
  docs/UG_Images/list_module2.png
  docs/UserGuide.md
  docs/team/zhu-ze-yu.md
Labels: type.Task

#257 fix ug and dg
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task

#255 Fix bug for including chapters and modules which are removed
  src/main/java/commands/IncludeCommand.java
  src/main/java/commands/RemoveChapterCommand.java
  src/main/java/commands/RemoveCommand.java
  src/main/java/commands/RemoveModuleCommand.java
  src/main/java/storage/Storage.java
  src/main/java/storage/StorageWrite.java
  src/test/java/commands/RemoveChapterCommandTest.java
  src/test/java/commands/RemoveModuleCommandTest.java
Labels: severity.Medium, type.Bug

#258 Change diagrams format and add javadoc
  docs/UserGuide.md
  src/main/java/commands/ListChaptersCommand.java
  src/main/java/exception/InvalidFileFormatException.java
  src/main/java/manager/history/History.java
  src/main/java/storage/Storage.java
  src/main/java/storage/StorageParser.java
  src/main/java/storage/StorageWrite.java
Labels: type.Task

#260 Updated guides
  docs/DG_Images/LogicClassDiagram.png
  docs/DeveloperGuide.md
  docs/README.md
  docs/UG_Images/AddCard1.png
  docs/UG_Images/AddCard2.png
  docs/UG_Images/AdminLevel.png
  docs/UG_Images/CLI.png
  docs/UG_Images/ChapterLevel.png
  docs/UG_Images/EditCard1.png
  docs/UG_Images/EditCard2.png
  docs/UG_Images/EditCard3.png
  docs/UG_Images/EditCard4.png
  docs/UG_Images/EditChapter1.png
  docs/UG_Images/EditChapter2.png
  docs/UG_Images/EditChapter3.png
  docs/UG_Images/EditChapter4.png
  docs/UG_Images/ListCard1.png
  docs/UG_Images/ListCard2.png
  docs/UG_Images/ModuleLevel.png
  docs/UG_Images/RescheduleChapter1.png
  docs/UG_Images/RescheduleChapter2.png
  docs/UG_Images/RescheduleChapter3.png
  docs/UG_Images/RescheduleChapter4.png
  docs/UML/LogicClassDiagram.puml
  docs/UserGuide.md
  docs/_config.yml
Labels: type.Task

#261 Update UG
  docs/DG_Images/storage.png
  docs/DeveloperGuide.md
  docs/UG_Images/back.png
  docs/UG_Images/backComplete.png
  docs/UG_Images/due.png
  docs/UG_Images/dueComplete.png
  docs/UG_Images/excludeChapter.png
  docs/UG_Images/excludeChapterChapter.png
  docs/UG_Images/excludeChapterChapterFilled.png
  docs/UG_Images/excludeChapterChapterPrompt.png
  docs/UG_Images/excludeChapterModule.png
  docs/UG_Images/excludeChapterModuleFilled.png
  docs/UG_Images/excludeChapterModulePrompt.png
  docs/UG_Images/excludeChapterResult.png
  docs/UG_Images/excludeModule.png
  docs/UG_Images/excludeModuleModule.png
  docs/UG_Images/excludeModuleModuleFilled.png
  docs/UG_Images/excludeModuleModulePrompt.png
  docs/UG_Images/excludeModuleResult.png
  docs/UG_Images/includeChapter.png
  docs/UG_Images/includeChapterChapter.png
  docs/UG_Images/includeChapterChapterFilled.png
  docs/UG_Images/includeChapterChapterPrompt.png
  docs/UG_Images/includeChapterModule.png
  docs/UG_Images/includeChapterModuleFilled.png
  docs/UG_Images/includeChapterModulePrompt.png
  docs/UG_Images/includeChapterResult.png
  docs/UG_Images/includeModule.png
  docs/UG_Images/includeModuleModule.png
  docs/UG_Images/includeModuleModuleFilled.png
  docs/UG_Images/includeModuleModulePrompt.png
  docs/UG_Images/includeModuleResult.png
  docs/UG_Images/moduleGo.png
  docs/UG_Images/moduleGoPrompt.png
  docs/UG_Images/moduleGoResult.png
  docs/UG_Images/preview.png
  docs/UG_Images/previewComplete.png
  docs/UML/includeClass.puml
  docs/UML/storage.puml
  docs/UserGuide.md
  src/main/java/commands/ExcludeCommand.java
  src/main/java/commands/IncludeCommand.java
  src/main/java/commands/ListDueCommand.java
  src/main/java/commands/PreviewCommand.java
  src/main/java/scheduler/Scheduler.java
  src/main/java/storage/StorageLoad.java
  src/main/java/storage/StorageWrite.java
Labels: type.Task

#263 Updated UG
  docs/UserGuide.md
Labels: type.Task

#264 Small edit to UG
  docs/UserGuide.md
Labels: type.Task

#265 update Jiayi's ppp
  docs/team/gua-guargia.md
Labels: type.Task

#269 Update PPP
  docs/team/jane-ng.md
Labels: type.Task
